### PR TITLE
Bookmark

### PR DESCRIPTION
**Pull request by gaurav618618**
- [x] Fixes issue #46 : "Add feature to save post"

## Reason for pull request:
"Required a feature so that user can save the post to read it later"

## Description of changes or additions:
"Implemented new view and template for viewing saved post, only authenticated user can save the post. "

## Screenshots:
"
saved
"

### CODE REVIEW

**Comment by deepak2431** [comment]
@gaurav618618 Please resolve the conflicts and update your PR.

**Comment by deepak2431** [comment]
@gaurav618618 I could not find any option to save the post. Can you please check and update your PR?
Thanks!

**Comment by gaurav618618** [comment]
Done

**Comment by deepak2431** [comment]
@gaurav618618 Looks fine to me now. I would request you to open a issue to remove the saved posts as there is no option for now to remove the saved posts.
Thanks!

**Review by deepak2431 — APPROVED** [review]

**Review by deepak2431 — APPROVED** [review]

**Review by deepak2431 — APPROVED** [review]

**Review by deepak2431 — APPROVED** [review]

**Comment by gaurav618618** [comment]
hey @deepak2431  the saved post can be removed using same button

**Pull request merged**
