### PR TITLE
added topic's section

### PR DESCRIPTION
**Pull request by Kartik-Sama**
modified:   blog/models.py
	modified:   blog/templates/blog/home.html
	modified:   blog/views.py
	new file:   blog/migrations/0004_post_topic.py

- [ ] Fixes issue #16  : "Add option to select topic."
- [x] Other checks

## Reason for pull request:
"To add a drop down menu for the topics section"

## Description of changes or additions:
"1)Added 'topic' field in blog/views.py
2)Added choices for topic in blog/models.py.
3)Corresponding migration file created after adding new column in database.

## Screenshots:
"Insert screenshots here if available"
homepage
createPost

### CODE REVIEW

**Comment by deepak2431** [comment]
@Kartik-Sama Still getting the same issue. Have you applied migrations ?
python manage.py makemigrations
python manage.py migrate
python manage.py runserver

Try these if it works fine. Test it after merging into the master after that make a PR. Thanks:)

**Comment by Kartik-Sama** [comment]
@deepak2431 I have made sure migrations are applied. I have cloned my forked repository in another location and have run:
python manage.py migrate
python manage.py runserver
And after this the website is opening normally even from the new location. Sorry for the inconvenience but I am unable to understand what error you are facing.

**Comment by Kartik-Sama** [comment]
Please check this I have switched to ubuntu and cloned the repository. It is working
Screenshot from 2019-12-17 20-23-16

**Comment by deepak2431** [comment]
@Kartik-Sama It's good to me now. Thanks a lot for all of your efforts. :)

**Pull request merged**
