### PR TITLE
add reset password feature

### PR DESCRIPTION
**Pull request by selvamanikannan**
- [x] Fixes issue #26:"Add option to recover password "
- [x] Other checks

## Reason for pull request:
"New Feature : reset password"

## Description of changes or additions:
"Gmail id has to be configured to sent reset mail"

### CODE REVIEW

**Comment by deepak2431** [comment]
@selvamanikannan I have reviewed your PR for sure you have made a lot of efforts. But I want you to make some changes:
1. Please remove the Forget Password option from navbar add in it the login page beside SignUp option.
2. Please remove the remove password options from the navbar if you want this to be available for users good to have it in the profile update page just ask for old password and new password to reset it.
3. I am getting error when I tried the forget password option. You can have a look over the error
Screenshot from 2019-12-14 12-26-05

**Comment by selvamanikannan** [comment]
> @selvamanikannan I have reviewed your PR for sure you have made a lot of efforts. But I want you to make some changes:
> 
> 1. Please remove the Forget Password option from navbar add in it the login page beside SignUp option.
> 2. Please remove the remove password options from the navbar if you want this to be available for users good to have it in the profile update page just ask for old password and new password to reset it.
> 3. I am getting error when I tried the forget password option. You can have a look over the error
>    Screenshot from 2019-12-14 12-26-05

pls add ur mail id and password in seetings.py
EMAIL_HOST_USER = 'your  gmail id'
EMAIL_HOST_PASSWORD = 'your  gmail pass'

line no 137,138

the allow low application at here https://myaccount.google.com/u/0/lesssecureapps?pageId=none
ensure ur gmail is not having two step authentication 
then run  the app it will work. 
i want to update you that i have tested properly 
waiting for your reply

**Comment by deepak2431** [comment]
> > @selvamanikannan I have reviewed your PR for sure you have made a lot of efforts. But I want you to make some changes:
> > 
> > 1. Please remove the Forget Password option from navbar add in it the login page beside SignUp option.
> > 2. Please remove the remove password options from the navbar if you want this to be available for users good to have it in the profile update page just ask for old password and new password to reset it.
> > 3. I am getting error when I tried the forget password option. You can have a look over the error
> >    Screenshot from 2019-12-14 12-26-05
> 
> pls add ur mail id and password in seetings.py
> EMAIL_HOST_USER = 'your gmail id'
> EMAIL_HOST_PASSWORD = 'your gmail pass'
> 
> line no 137,138
> 
> the allow low application at here https://myaccount.google.com/u/0/lesssecureapps?pageId=none
> ensure ur gmail is not having two step authentication
> then run the app it will work.
> i want to update you that i have tested properly
> waiting for your reply

Still getting same error. I will look over it. Till that can you please update the PR with other changes.

**Comment by deepak2431** [comment]
Good to me. Thanks :)

**Pull request merged**
