### PR TITLE
Fixes issue #14:"Add features to add image"

### PR DESCRIPTION
**Pull request by nikunjagarwal321**

### CODE REVIEW

**Comment by deepak2431** [comment]
@nikunjagarwal321 I have tested your patch you have done a great work. Only few issues
1: Users can only upload one pic for now ( Expected behavior: He should be able to upload as many as images.)
2. The images are only displayed on the top. There should be an option to add images while writing images inbetween too.
Thanks!

**Comment by deepak2431** [comment]
@nikunjagarwal321 Why have you closed this issue. You really have done a great work man. Just it required some more efforts to complete this. You have done 70% of the work only it require more 30% of work to be done. I would say you to reopen this issue and work over it. Feel free to reach me out in case of any difficulty.
Thanks!

**Comment by nikunjagarwal321** [comment]
@deepak2431 I'll try to implement the first point. Also, I found out that to fulfill the second point(add images anywhere), Vanilla.js is to be used. Is there any other way using django to do that?

**Comment by deepak2431** [comment]
@nikunjagarwal321 Try to implement the first one. As I am planning to move the whole application with react soon.So, if I would find anything for second one I would share with you that. You can also have a look over other issues as I think you are good with the basics of django. Thanks :)

**Comment by nikunjagarwal321** [comment]
@deepak2431 Sure. Will do that.

**Pull request closed without merging**
