### PR TITLE
Fixes issue #14 : "Add features to add image"

### PR DESCRIPTION
**Pull request by nikunjagarwal321**
- [x ] Fixes issue #IssueNo : "Name of issue here"
- [x] Other checks

## Reason for pull request:
"To add mutiple images in a post"

## Description of changes or additions:
"For now, a maximum of 6 images can be uploaded. We can increase this maximum limit easily. The only problem is while updating, one has to upload all the images again."

## Screenshots:
"Insert screenshots here if available"

### CODE REVIEW

**Comment by deepak2431** [comment]
@nikunjagarwal321 There's some merge conflict please resolve it and update your PR.

**Comment by nikunjagarwal321** [comment]
@deepak2431 I have resolved the merge conflicts. Please check once.

**Comment by deepak2431** [comment]
@nikunjagarwal321 You have put a lot of efforts for sure. But all the images are displayed on the top. Can you please make it to add images inbetween of the post too as I think it would be easy for you now. Thanks:)

**Comment by deepak2431** [comment]
@nikunjagarwal321 Thanks!

**Pull request merged**
