### PR TITLE
Home page 

### PR DESCRIPTION
**Pull request by snehalkhandve**
- [x] Fixes issue #13  : "Improve the home page
Screenshot from 2019-12-14 01-23-07
"
- [x] Other checks

## Reason for pull request:
"Why was this pull request created"

## Description of changes or additions:
"Insert description of changes made in this pull request here"

## Screenshots:
"Insert screenshots here if available"

### CODE REVIEW

**Comment by deepak2431** [comment]
Screenshot from 2019-12-14 19-20-25
@snehalkhandve I have tested your PR. Your CSS rules are not getting loaded. You can check the images above.
Thanks :)

**Comment by snehalkhandve** [comment]
Heyy , can you please suggest me some commands that will not upload all the virtualenv files also.
Because my code is working fine on local machine but while pushing I had deleted some virtualenv files which may had led to CSS files not loading on your machine . 
Please suggest changes .

**Comment by deepak2431** [comment]
@snehalkhandve Sure, can you please connect on the gitter. You can ask any questions over there. If you still have any questions reach me out on gitter through DM. Thanks :)

**Comment by snehalkhandve** [comment]
@deepak2431 can you please verify this pr . I have deleted virtualenv folder .

**Comment by deepak2431** [comment]
Screenshot from 2019-12-15 13-56-14
Screenshot from 2019-12-15 13-56-26


@snehalkhandve Your styles are being applied now. I think you are now comfortablw working with venev. Just you need to make the following changes
1. As shown in the image above the text Sign in is not visible change it's color to black.
2. You have applied some styles to comment section as it really looks good to me know but you have removed the captcha so for this purpose you also need to make some chnages in settings file as now I am getting error while submitting the comment.
Please fix this and update this PR. I am looking forward to merge it now.
Thanks  :)

**Comment by snehalkhandve** [comment]
I have made the changes .

**Comment by deepak2431** [comment]
@snehalkhandve Still there's some issue to be resolved. Can you please check it once and update the PR?
Screenshot from 2019-12-15 18-46-48
Screenshot from 2019-12-15 18-43-04

**Comment by snehalkhandve** [comment]
I had issues with previous git repo hence forked again and created a new pull request #37 for same issue #13 . I have made all the checks and the site works fine . Please review pr #37 and merge :P

**Comment by deepak2431** [comment]
Resolved in #37

**Pull request closed without merging**
