### PR TITLE
Adding reply

### PR DESCRIPTION
**Pull request by gaurav618618**
- [x] Fixes issue #34  : "Added reply to comments"

## Reason for pull request:
"Needed a reply option to the comment"

## Description of changes or additions:
"Inserted new field to comment model to store the id of the parent comment and then added for loop to print every child(reply) comment for every parent comment 

 "

## Screenshots:
"comment"

### CODE REVIEW

**Comment by deepak2431** [comment]
@gaurav618618 Please resolve the merge conflicts and update your PR.

**Comment by gaurav618618** [comment]
I have resolved all the conflicts.

**Comment by deepak2431** [comment]
Screenshot from 2019-12-19 11-49-07
I am not able to run the server. Please test your PR before making final PR. Thanks:)

**Comment by gaurav618618** [comment]
I have updated the code it was just a ",".

**Comment by deepak2431** [comment]
@gaurav618618 It looks good to me. As I want you to make following small changes:
When I clicked on reply the comment form is also visible as only all the replied should be visible. So, for this I would suggest add two option Add new reply, Reply. Don't make the reply button visible until any reply has been added. Only after clicking the Add new reply the comment form should be visible.
Thanks :)

**Comment by deepak2431** [comment]
@gaurav618618 It's good to me now. Thanks :)

**Pull request merged**
