### PR TITLE
Added topic column in create Post.

### PR DESCRIPTION
**Pull request by Kartik-Sama**
#16 
	modified:   blog/views.py
	blog/migrations/0004_post_topic.py

- [ ] Fixes issue #IssueNo 16 : "Add option to select topic."
- [x] Other checks

## Reason for pull request:
"To add a drop down menu for the topics section"

## Description of changes or additions:
1)Added 'topic' field in blog/views.py
2)Added choices for topic in blog/models.py.
3)Corresponding migration file created after adding new column in database.

##Addition of topics:
To a new topic go to blog/models.py and add a tuple (of format("NEW","new")) to TOPICS list in the post class.

### CODE REVIEW

**Comment by deepak2431** [comment]
@Kartik-Sama You have done a great job as I am now able to select topic while writing the post. Good to display the topic along with the post so the users can get a quick view of what a post is about.

**Comment by Kartik-Sama** [comment]
delete
I have displayed topic in posts. Hope this is what you wanted.

**Comment by deepak2431** [comment]
Screenshot from 2019-12-16 20-54-03

@Kartik-Sama I am not able to test your PR as I think you haven't applied all the migrations before making PR. Please update your PR again. The PR is as per what I have expected. Thanks :)

**Comment by Kartik-Sama** [comment]
Sorry, I forgot to apply migrations before updating changes. Please consider the updated files with new migrations.

**Comment by deepak2431** [comment]
@Kartik-Sama Still getting the same error. Check it out and update your PR.

**Comment by deepak2431** [comment]
Screenshot from 2019-12-16 21-40-59
Please check everything once before making final commit. Thanks :)

**Comment by Kartik-Sama** [comment]
Sorry but I amn't able to figure out the error.

**Comment by Kartik-Sama** [comment]
@deepak2431 , Please run python manage.py migrate before python manage.py runserver. It should remove the Operational Error. Please inform if the problem still persists.

**Comment by deepak2431** [comment]
@Kartik-Sama I am still getting the same issue. Can you please again once forked this repo and delete old one and make a PR after making changes from a new branch. Thanks:)

**Pull request closed without merging**
